version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: family-calendar-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: family_calendar
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://localhost:5173,http://localhost
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - family-calendar-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.family-calendar.wawro.ovh`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: family-calendar-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - family-calendar-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`family-calendar.wawro.ovh`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

volumes:
  postgres_data:

networks:
  family-calendar-network:
    driver: bridge